/*
 * Icon — the kebab-case lucide registry.
 *
 * The seeded data carries lucide names as authored in the comp
 * (`life-buoy`, `check-circle-2`, …), so the registry maps those strings to
 * `lucide-react` components. Imports are explicit so the bundle only carries
 * the icons the app actually uses; an unknown name renders `Circle`.
 *
 * Need an icon that is not here? Add the import and one registry line.
 */

import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BadgeCheck,
  Banknote,
  Battery,
  BatteryLow,
  Bell,
  BellOff,
  BellRing,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  BookmarkPlus,
  BookmarkX,
  Bot,
  Box,
  Boxes,
  Building2,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarOff,
  CalendarPlus,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronRight,
  Circle,
  CircleDot,
  CircleUser,
  ClipboardCheck,
  Clock,
  Command,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  DoorOpen,
  Download,
  Eye,
  FileCheck,
  FileText,
  Flame,
  Frown,
  Gift,
  GraduationCap,
  HardHat,
  Headset,
  Heart,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyRound,
  Keyboard,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Lock,
  LogOut,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minus,
  Monitor,
  Moon,
  Package,
  PackageCheck,
  PackageSearch,
  Palette,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  Pin,
  Plug,
  PlugZap,
  Plus,
  PlusCircle,
  Presentation,
  QrCode,
  Radar,
  Radio,
  Recycle,
  Reply,
  RotateCcw,
  Ruler,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBasket,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  SunMoon,
  Tablet,
  TabletSmartphone,
  Tag,
  Target,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundCog,
  Users,
  Video,
  Wallet,
  Wifi,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  battery: Battery,
  "battery-low": BatteryLow,
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  "bookmark-plus": BookmarkPlus,
  "bookmark-x": BookmarkX,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  "building-2": Building2,
  cake: Cake,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  check: Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-dot": CircleDot,
  "circle-user": CircleUser,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  command: Command,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  "door-open": DoorOpen,
  download: Download,
  eye: Eye,
  "file-check": FileCheck,
  "file-text": FileText,
  flame: Flame,
  frown: Frown,
  gift: Gift,
  "graduation-cap": GraduationCap,
  "hard-hat": HardHat,
  headset: Headset,
  heart: Heart,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  keyboard: Keyboard,
  laptop: Laptop,
  layers: Layers,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  library: Library,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  "log-out": LogOut,
  magnet: Magnet,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  meh: Meh,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  "package-check": PackageCheck,
  "package-search": PackageSearch,
  palette: Palette,
  paperclip: Paperclip,
  "pen-line": PenLine,
  pencil: Pencil,
  phone: Phone,
  pin: Pin,
  plug: Plug,
  "plug-zap": PlugZap,
  plus: Plus,
  "plus-circle": PlusCircle,
  presentation: Presentation,
  "qr-code": QrCode,
  radar: Radar,
  radio: Radio,
  recycle: Recycle,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-basket": ShoppingBasket,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  store: Store,
  sun: Sun,
  "sun-moon": SunMoon,
  tablet: Tablet,
  "tablet-smartphone": TabletSmartphone,
  tag: Tag,
  target: Target,
  thermometer: Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  timer: Timer,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-cog": UserRoundCog,
  users: Users,
  video: Video,
  wallet: Wallet,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
};

export interface IconProps {
  /** Kebab-case lucide name, e.g. `life-buoy`. */
  name: string;
  /** Pixel size. Defaults to 16. */
  size?: number;
  color?: string;
  className?: string;
  strokeWidth?: number;
}

export function Icon({
  name,
  size = 16,
  color,
  className,
  strokeWidth = 2,
}: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return (
    <Cmp
      size={size}
      color={color}
      className={className}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      focusable="false"
    />
  );
}

export default Icon;
