/*
 * Icon — the kebab-case lucide registry.
 *
 * The seeded data carries lucide names as authored in the comp
 * (`life-buoy`, `check-circle-2`, …), so the registry maps those strings to
 * `lucide-react` components. Imports are explicit so the bundle only carries
 * the icons the app actually uses; an unknown name renders `Circle`.
 *
 * Need an icon that is not here? Add the import and one registry line.
 */

import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  Battery,
  BatteryLow,
  Bell,
  BellOff,
  BellRing,
  Bookmark,
  BookmarkCheck,
  BookmarkPlus,
  BookmarkX,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Building2,
  Cable,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarOff,
  CalendarPlus,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronRight,
  Circle,
  CircleDot,
  CircleUser,
  ClipboardCheck,
  Clock,
  CloudLightning,
  CloudOff,
  Command,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  DoorOpen,
  Download,
  Eraser,
  Eye,
  FileArchive,
  FileCheck,
  FileText,
  Flag,
  Flame,
  Frown,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  HardHat,
  Hash,
  Headset,
  Heart,
  HeartOff,
  HelpCircle,
  History,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  Keyboard,
  KeyRound,
  Lamp,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2Off,
  List,
  Loader,
  LocateFixed,
  Lock,
  LogIn,
  LogOut,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  MapPinOff,
  Maximize,
  Medal,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Minus,
  Monitor,
  MonitorOff,
  MonitorSmartphone,
  Moon,
  Navigation,
  Package,
  PackageCheck,
  PackageOpen,
  PackageSearch,
  PackageX,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  PenLine,
  Percent,
  Phone,
  Pin,
  Play,
  Plug,
  PlugZap,
  Plus,
  PlusCircle,
  Presentation,
  QrCode,
  Radar,
  Radio,
  Receipt,
  Recycle,
  RefreshCw,
  Repeat,
  Reply,
  RotateCcw,
  Ruler,
  Scale,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Smile,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  SunMoon,
  Sunset,
  Tablet,
  TabletSmartphone,
  Tag,
  Target,
  Thermometer,
  ThermometerSnowflake,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundCog,
  Users,
  UserX,
  Video,
  VideoOff,
  Volume2,
  Wallet,
  Wifi,
  WifiOff,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  award: Award,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  battery: Battery,
  "battery-low": BatteryLow,
  bell: Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  "bookmark-plus": BookmarkPlus,
  "bookmark-x": BookmarkX,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  "building-2": Building2,
  cable: Cable,
  cake: Cake,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  camera: Camera,
  check: Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-dot": CircleDot,
  "circle-help": HelpCircle,
  "circle-user": CircleUser,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  "cloud-lightning": CloudLightning,
  "cloud-off": CloudOff,
  command: Command,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  "door-open": DoorOpen,
  download: Download,
  eraser: Eraser,
  eye: Eye,
  "file-archive": FileArchive,
  "file-check": FileCheck,
  "file-text": FileText,
  flag: Flag,
  flame: Flame,
  frown: Frown,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hard-hat": HardHat,
  hash: Hash,
  headset: Headset,
  heart: Heart,
  "heart-off": HeartOff,
  history: History,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  keyboard: Keyboard,
  lamp: Lamp,
  laptop: Laptop,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  library: Library,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  "link-2-off": Link2Off,
  list: List,
  loader: Loader,
  "locate-fixed": LocateFixed,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  magnet: Magnet,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  "map-pin-off": MapPinOff,
  maximize: Maximize,
  medal: Medal,
  meh: Meh,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  mic: Mic,
  minus: Minus,
  monitor: Monitor,
  "monitor-off": MonitorOff,
  "monitor-smartphone": MonitorSmartphone,
  moon: Moon,
  navigation: Navigation,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  "package-search": PackageSearch,
  "package-x": PackageX,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  "pen-line": PenLine,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  pin: Pin,
  play: Play,
  plug: Plug,
  "plug-zap": PlugZap,
  plus: Plus,
  "plus-circle": PlusCircle,
  presentation: Presentation,
  "qr-code": QrCode,
  radar: Radar,
  radio: Radio,
  receipt: Receipt,
  recycle: Recycle,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  "search-check": SearchCheck,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  store: Store,
  sun: Sun,
  "sun-moon": SunMoon,
  sunset: Sunset,
  tablet: Tablet,
  "tablet-smartphone": TabletSmartphone,
  tag: Tag,
  target: Target,
  thermometer: Thermometer,
  "thermometer-snowflake": ThermometerSnowflake,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  timer: Timer,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-cog": UserRoundCog,
  "user-x": UserX,
  users: Users,
  video: Video,
  "video-off": VideoOff,
  "volume-2": Volume2,
  wallet: Wallet,
  wifi: Wifi,
  "wifi-off": WifiOff,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
};

export interface IconProps {
  /** Kebab-case lucide name, e.g. `life-buoy`. */
  name: string;
  /** Pixel size. Defaults to 16. */
  size?: number;
  color?: string;
  className?: string;
  strokeWidth?: number;
}

export function Icon({
  name,
  size = 16,
  color,
  className,
  strokeWidth = 2,
}: IconProps) {
  const Cmp = ICONS[name] ?? Circle;
  return (
    <Cmp
      size={size}
      color={color}
      className={className}
      strokeWidth={strokeWidth}
      aria-hidden="true"
      focusable="false"
    />
  );
}

export default Icon;
